#!/usr/bin/env python3
"""
Remove visible SEO brief markers and JSON-LD code blocks from articleContent.ts.
Also apply business-blocker facts to any remaining placeholders.

Run: python3 scripts/clean-article-content-markers.py
"""

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ARTICLE_CONTENT_PATH = REPO / "src/data/content/articleContent.ts"


def read_article_content(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.search(
        r"export const ARTICLE_CONTENT: Record<string, string> = (\{.*\})\n",
        text,
        re.DOTALL,
    )
    if not m:
        return {}
    data: dict[str, str] = {}
    for km in re.finditer(r'"([^"]+)"\s*:\s*"((?:[^"\\]|\\.)*)"', m.group(1)):
        data[km.group(1)] = json.loads('"' + km.group(2) + '"')
    return data


def serialize_article_content(data: dict[str, str]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/publish-content.py — edit source markdown, not this file.\n",
        "/** Full article HTML bodies, keyed by route path. Imported ONLY by the lazy",
        " *  article renderer and the build-time inject-meta step — never the eager nav bundle. */",
        "export const ARTICLE_CONTENT: Record<string, string> = {",
    ]
    for i, (key, value) in enumerate(sorted(data.items())):
        comma = "," if i < len(data) - 1 else ""
        lines.append(f'  "{key}": {json.dumps(value, ensure_ascii=False)}{comma}')
    lines.append("}\n")
    return "\n".join(lines)


def clean_html(html: str, route: str = "") -> str:
    # 1. Remove horizontal-rule + JSON-LD heading + following code block (greedy but careful)
    # Matches <hr /> optionally followed by whitespace, then a heading like
    # <h2 id="...">3. SUGGESTED STRUCTURED DATA (JSON-LD)</h2> or similar,
    # then a <pre><code class="language-json">...</code></pre> block.
    patterns = [
        # hr + heading + pre/code JSON
        r"<hr\s*/?>\s*(?:<h[1-6][^>]*>\s*\d+\.\s*(?:SUGGESTED STRUCTURED DATA|JSON-LD SNIPPET|JSON-LD).*?</h[1-6]>\s*)?<pre><code[^>]*>\s*\{.*?\}\s*</code></pre>",
        # heading without hr
        r"<h[1-6][^>]*>\s*\d+\.\s*(?:SUGGESTED STRUCTURED DATA|JSON-LD SNIPPET|JSON-LD).*?</h[1-6]>\s*<pre><code[^>]*>\s*\{.*?\}\s*</code></pre>",
        # generic JSON-LD code block (starts with {)
        r"<pre><code[^>]*>\s*\{.*?\}\s*</code></pre>",
        # hr + "SUGGESTED STRUCTURED DATA" heading and everything after it (implementation notes/schema guidance)
        r"<hr\s*/?>\s*<h[1-6][^>]*>(?:\s*\d+\.\s*)?(?:SUGGESTED STRUCTURED DATA|JSON-LD SNIPPET|JSON-LD).*?</h[1-6]>.*",
    ]
    for pat in patterns:
        html = re.sub(pat, "", html, flags=re.DOTALL | re.IGNORECASE)

    # 2. Remove visible Title tag / Meta description paragraphs
    html = re.sub(
        r"<p>\s*<strong>Title\s*(?:tag)?:</strong>.*?</p>",
        "",
        html,
        flags=re.IGNORECASE | re.DOTALL,
    )
    html = re.sub(
        r"<p>\s*<strong>Meta\s*description:</strong>.*?</p>",
        "",
        html,
        flags=re.IGNORECASE | re.DOTALL,
    )

    # 3. Apply business blocker facts (allow text before/after the marker)
    html = re.sub(
        r"\[[^\]]*BUSINESS CONFIRMATION REQUIRED[^\]]*deposit[^\]]*\]",
        "A 50% deposit confirms your date",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[[^\]]*BUSINESS CONFIRMATION REQUIRED[^\]]*(?:found|established|since)[^\]]*\]",
        "2019",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[[^\]]*BUSINESS CONFIRMATION REQUIRED[^\]]*villa chef[^\]]*\]",
        "Villa chef service starts from IDR 2,000,000 for a half-day and IDR 4,000,000 for a full day",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[[^\]]*BUSINESS CONFIRMATION REQUIRED[^\]]*corporate[^\]]*minimum[^\]]*\]",
        "Corporate events have a minimum spend of IDR 50,000,000",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[[^\]]*BUSINESS CONFIRMATION REQUIRED[^\]]*placement fee[^\]]*\]",
        "Placement fees are discussed once we understand the role and candidate requirements",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[[^\]]*BUSINESS CONFIRMATION REQUIRED[^\]]*(?:from-price|approve|worked example|recurring contract)[^\]]*\]",
        "Contact us for current pricing",
        html,
        flags=re.IGNORECASE,
    )
    # Delivery outside Bali — handled case by case (BALI-ONLY: do not re-add Jakarta)
    html = re.sub(
        r"\[[^\]]*BUSINESS CONFIRMATION REQUIRED[^\]]*outside Bali[^\]]*currently handled case by case[^\]]*\]",
        "contact us for destinations outside Bali",
        html,
        flags=re.IGNORECASE,
    )
    # Remove any remaining unresolved placeholders
    html = re.sub(r"\[[^\]]*BUSINESS CONFIRMATION REQUIRED[^\]]*\]", "", html, flags=re.IGNORECASE)
    # Clean up empty emphasis tags left behind
    html = re.sub(r"<em>\s*</em>", "", html, flags=re.IGNORECASE)
    html = re.sub(r"<em>\s*</em>\s*</p>", "</p>", html, flags=re.IGNORECASE)

    # 4. Clean up double/triple newlines and trailing whitespace
    html = re.sub(r"\n{3,}", "\n\n", html)
    html = re.sub(r"  +", " ", html)
    html = html.strip()

    return html


def main():
    article_content = read_article_content(ARTICLE_CONTENT_PATH)
    cleaned_count = 0

    for route, html in article_content.items():
        cleaned = clean_html(html, route)
        if cleaned != html:
            article_content[route] = cleaned
            cleaned_count += 1

    ARTICLE_CONTENT_PATH.write_text(serialize_article_content(article_content), encoding="utf-8")
    print(f"Cleaned {cleaned_count} of {len(article_content)} article entries.")


if __name__ == "__main__":
    main()
