/**
 * ONE-TIME migration: split heavy article `content` out of the eagerly-imported
 * data arrays so it no longer ships in the index chunk on every page.
 *
 * Reads the current (content-bearing) arrays and emits:
 *   - src/data/content/articleContent.ts  → ARTICLE_CONTENT keyed by route path
 *   - src/data/content/{landingPages,guides,blogPosts,journalPosts}.ts → content-free metadata
 *
 * After this runs, sitemap.ts / siteArchitecture.ts import the content-free
 * metadata (eager, tiny) and only the lazy article renderer + the build-time
 * inject-meta step pull ARTICLE_CONTENT. Prerendered HTML stays byte-identical.
 *
 * Run: npx tsx scripts/gen-split-content.ts   (not part of the normal build)
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { LANDING_PAGES, GUIDES, BLOG_POSTS } from '../src/data/sitemap'
import { JOURNAL_POSTS } from '../src/data/siteArchitecture'

const OUT = resolve(process.cwd(), 'src/data/content')
mkdirSync(OUT, { recursive: true })

const HEADER = '// AUTO-GENERATED by scripts/gen-split-content.ts — edit the split source, not a merged copy.\n'

type AnyPost = Record<string, unknown> & { slug: string; content?: string }

const content: Record<string, string> = {}
const collect = (posts: AnyPost[], keyer: (p: AnyPost) => string) => {
  for (const p of posts) {
    if (typeof p.content === 'string') content[keyer(p)] = p.content
  }
}
collect(LANDING_PAGES as AnyPost[], (p) => `/${p.slug}`)
collect(GUIDES as AnyPost[], (p) => `/${p.slug}`)
collect(BLOG_POSTS as AnyPost[], (p) => `/${p.slug}`)
collect(JOURNAL_POSTS as AnyPost[], (p) => `/journal/${p.slug}`)

const stripContent = (posts: AnyPost[]) =>
  posts.map(({ content: _, ...rest }) => rest)

writeFileSync(
  resolve(OUT, 'articleContent.ts'),
  HEADER +
    '/** Full article HTML bodies, keyed by route path. Imported ONLY by the lazy\n' +
    ' *  article renderer and the build-time inject-meta step — never the eager nav bundle. */\n' +
    `export const ARTICLE_CONTENT: Record<string, string> = ${JSON.stringify(content, null, 2)}\n`
)

writeFileSync(
  resolve(OUT, 'landingPages.ts'),
  HEADER +
    "import type { ContentEntry } from '@/lib/blog'\n\n" +
    `export const LANDING_PAGES: ContentEntry[] = ${JSON.stringify(stripContent(LANDING_PAGES as AnyPost[]), null, 2)}\n`
)
writeFileSync(
  resolve(OUT, 'guides.ts'),
  HEADER +
    "import type { ContentEntry } from '@/lib/blog'\n\n" +
    `export const GUIDES: ContentEntry[] = ${JSON.stringify(stripContent(GUIDES as AnyPost[]), null, 2)}\n`
)
writeFileSync(
  resolve(OUT, 'blogPosts.ts'),
  HEADER +
    "import type { ContentEntry } from '@/lib/blog'\n\n" +
    `export const BLOG_POSTS: ContentEntry[] = ${JSON.stringify(stripContent(BLOG_POSTS as AnyPost[]), null, 2)}\n`
)
writeFileSync(
  resolve(OUT, 'journalPosts.ts'),
  HEADER +
    "import type { JournalPost } from '@/data/siteArchitecture'\n\n" +
    `export const JOURNAL_POSTS: JournalPost[] = ${JSON.stringify(stripContent(JOURNAL_POSTS as AnyPost[]), null, 2)}\n`
)

console.log('generated content/ modules:')
console.log('  ARTICLE_CONTENT entries:', Object.keys(content).length)
console.log('  landingPages:', LANDING_PAGES.length, 'guides:', GUIDES.length, 'blogPosts:', BLOG_POSTS.length, 'journalPosts:', JOURNAL_POSTS.length)
