#!/usr/bin/env tsx
/**
 * ONE-TIME generator: freezes a stable per-page lastmod map for the pages that
 * currently exist but have no real content date.
 *
 * Policy (per owner decision):
 *   - Pages WITH a real content date (blog/journal/guides) → use that (handled in
 *     generate-sitemap.ts, not here). [B / real]
 *   - Pages WITHOUT one → get a STABLE, deterministic date spread across the site's
 *     REAL active development window (2026-05-13 … 2026-06-28), so the sitemap isn't
 *     all one date. Deterministic (hash of path) → same date every deploy. [C-lite,
 *     bounded to the true window — NOT a fabricated 7-month backdate, which Google
 *     ignores when it predates first crawl.]
 *   - FUTURE new pages: not in this frozen map and no real date → generate-sitemap
 *     omits lastmod. [A — the default going forward]
 *
 * Re-run ONLY if you deliberately want to fold newly-added pages into the spread.
 * Normal deploys must NOT run this — they just read the committed map.
 */

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { SITEMAP, type SitemapEntry } from '../src/data/sitemap'
import { JOURNAL_POSTS } from '../src/data/siteArchitecture'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Real active development window (git history: first commit 2026-05-13).
const WINDOW_START = Date.parse('2026-05-13T00:00:00Z')
const WINDOW_END = Date.parse('2026-06-28T00:00:00Z')
const SPAN_DAYS = Math.round((WINDOW_END - WINDOW_START) / 86_400_000)

// djb2 — stable across runs/machines.
function hash(s: string): number {
  let h = 5381
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) >>> 0
  return h
}

function spreadDate(path: string): string {
  const offset = hash(path) % (SPAN_DAYS + 1)
  return new Date(WINDOW_START + offset * 86_400_000).toISOString().split('T')[0]
}

const entries: { path: string; date?: string }[] = [
  ...SITEMAP.map((e: SitemapEntry) => ({ path: e.path, date: e.date })),
  ...JOURNAL_POSTS.map((p) => ({ path: `/journal/${p.slug}`, date: p.date })),
]

const map: Record<string, string> = {}
let dated = 0
for (const e of entries) {
  if (e.date) { dated++; continue }   // real date → handled by generate-sitemap (B)
  if (map[e.path]) continue
  map[e.path] = spreadDate(e.path)      // deterministic spread (C-lite)
}

const out = `// AUTO-GENERATED by scripts/generate-lastmod-map.ts — do not edit by hand.
// Frozen lastmod dates for pages without a real content date (owner-requested spread).
// New pages NOT listed here fall back to omitting <lastmod> (policy A).
export const SITEMAP_LASTMOD: Record<string, string> = ${JSON.stringify(map, null, 2)}
`
writeFileSync(join(__dirname, '..', 'src', 'data', 'sitemap-lastmod.ts'), out)

const dist = Object.values(map).reduce<Record<string, number>>((a, d) => ((a[d.slice(0, 7)] = (a[d.slice(0, 7)] || 0) + 1), a), {})
console.log(`Froze ${Object.keys(map).length} spread dates (+${dated} pages keep real dates).`)
console.log('By month:', dist)
