#!/usr/bin/env python3
"""
Publish mychef-seo/content/ hub-page files into the myCHEF system.

Processes main/hardcoded page content files and injects ArticleContentSection
into the corresponding page components.

Run: python3 scripts/publish-hub-content.py
"""

import json
import re
from pathlib import Path
import markdown

REPO = Path(__file__).resolve().parent.parent
SEO = Path("/Users/openclaw/Movies/LIve website/mychef-seo")
CONTENT_DIR = SEO / "content"
ARTICLE_CONTENT_PATH = REPO / "src/data/content/articleContent.ts"
PAGES_DIR = REPO / "src/pages"

# Map content filename to canonical route and page component
HUB_FILES = {
    "home.md": ("/", "HubPage.tsx"),
    "pricing.md": ("/pricing", "PricingPage.tsx"),
    "services.md": ("/services", "ServicesPage.tsx"),
    "why-mychef.md": ("/why-mychef", "WhyMychefPage.tsx"),
    "faq.md": ("/faq", "FAQPage.tsx"),
    "reviews.md": ("/reviews", "ReviewsPage.tsx"),
    "villa-chef.md": ("/villa-chef", "SolPage.tsx"),
    "catering.md": ("/catering", "CateringPage.tsx"),
    "events.md": ("/events", "EventsMainPage.tsx"),
    "fine-dining.md": ("/fine-dining", "LunaPage.tsx"),
    "experiences.md": ("/experiences", "ExperiencesHubPage.tsx"),
    "in-villa-service.md": ("/in-villa-service", "InVillaServicePage.tsx"),
    "staffing.md": ("/staffing", "StaffingPage.tsx"),
}


def extract_replacement_content(text: str) -> str:
    """Return the publishable markdown after the FULL REPLACEMENT CONTENT marker,
    stopping at the first '---' separator (e.g. before JSON-LD sections)."""
    markers = [
        r"##\s+FULL REPLACEMENT CONTENT",
        r"#\s+FULL REPLACEMENT CONTENT",
        r"##\s+2\.\s*FULL REPLACEMENT CONTENT",
    ]
    for marker in markers:
        m = re.search(marker, text, re.IGNORECASE)
        if m:
            content = text[m.end():]
            # Stop at the first horizontal-rule separator that follows the marker
            content = re.split(r"\n---\s*\n", content, maxsplit=1)[0]
            content = re.sub(r"\*\*Title tag:\*\*.*?\n", "", content)
            content = re.sub(r"\*\*Meta description:\*\*.*?\n", "", content)
            return content.strip()
    parts = re.split(r"\n---\s*\n", text, maxsplit=2)
    if len(parts) >= 2:
        return parts[-1].strip()
    return text.strip()


def md_to_html(text: str) -> str:
    md = markdown.Markdown(extensions=["tables", "fenced_code", "toc"])
    return md.convert(text)


def read_article_content(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.search(
        r"export const ARTICLE_CONTENT: Record<string, string> = (\{.*\})\n",
        text,
        re.DOTALL,
    )
    if not m:
        return {}
    data: dict[str, str] = {}
    for km in re.finditer(r'"([^"]+)"\s*:\s*"((?:[^"\\]|\\.)*)"', m.group(1)):
        data[km.group(1)] = json.loads('"' + km.group(2) + '"')
    return data


def serialize_article_content(data: dict[str, str]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/publish-content.py — edit source markdown, not this file.\n",
        "/** Full article HTML bodies, keyed by route path. Imported ONLY by the lazy",
        " *  article renderer and the build-time inject-meta step — never the eager nav bundle. */",
        "export const ARTICLE_CONTENT: Record<string, string> = {",
    ]
    for i, (key, value) in enumerate(sorted(data.items())):
        comma = "," if i < len(data) - 1 else ""
        lines.append(f'  "{key}": {json.dumps(value, ensure_ascii=False)}{comma}')
    lines.append("}\n")
    return "\n".join(lines)


def apply_business_blockers(html: str, route: str = "") -> str:
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*deposit[^\]]*\]",
        "A 50% deposit confirms your date",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*(?:found|established|since)[^\]]*\]",
        "2019",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*villa chef[^\]]*\]",
        "Villa chef service starts from IDR 2,000,000 for a half-day and IDR 4,000,000 for a full day",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*corporate[^\]]*minimum[^\]]*\]",
        "Corporate events have a minimum spend of IDR 50,000,000",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*placement fee[^\]]*\]",
        "Placement fees are discussed once we understand the role and candidate requirements",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*(?:from-price|approve|worked example|recurring contract)[^\]]*\]",
        "Contact us for current pricing",
        html,
        flags=re.IGNORECASE,
    )
    html = re.sub(r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*\]", "", html, flags=re.IGNORECASE)
    html = re.sub(r"\n{3,}", "\n\n", html)
    html = re.sub(r"  +", " ", html)
    return html


def patch_page(page_path: Path) -> None:
    text = page_path.read_text(encoding="utf-8")
    if "ArticleContentSection" in text:
        return

    import_line = "import { ArticleContentSection } from '@/components/shared'"
    if import_line.split("from")[0].strip() not in text:
        last_import = text.rfind("import ")
        if last_import != -1:
            end = text.index("\n", last_import) + 1
            text = text[:end] + import_line + "\n" + text[end:]
        else:
            text = import_line + "\n" + text

    # Try to insert before the final closing div of the main return
    text = re.sub(
        r"(\n)(\s*)</div>\n(\s*)\)\n\}$",
        r"\1\2<ArticleContentSection />\n\2</div>\n\3)\n}",
        text,
        count=1,
    )
    page_path.write_text(text, encoding="utf-8")


def main():
    article_content = read_article_content(ARTICLE_CONTENT_PATH)
    updated = 0
    skipped = 0

    for filename, (route, page_file) in sorted(HUB_FILES.items()):
        md_path = CONTENT_DIR / filename
        if not md_path.exists():
            skipped += 1
            print(f"SKIP (missing): {filename}")
            continue

        md_text = md_path.read_text(encoding="utf-8")
        replacement_md = extract_replacement_content(md_text)
        if not replacement_md:
            skipped += 1
            print(f"SKIP (empty): {filename}")
            continue

        html = md_to_html(replacement_md)
        html = apply_business_blockers(html, route)
        article_content[route] = html
        updated += 1
        print(f"PUBLISHED: {route} ({len(html)} chars HTML)")

        page_path = PAGES_DIR / page_file
        if page_path.exists():
            patch_page(page_path)
            print(f"  PATCHED: {page_file}")
        else:
            print(f"  PAGE MISSING: {page_file}")

    ARTICLE_CONTENT_PATH.write_text(
        serialize_article_content(article_content), encoding="utf-8"
    )

    print(f"\nDone. Updated {updated} hub entries, skipped {skipped}.")


if __name__ == "__main__":
    main()
