#!/usr/bin/env python3
"""
Publish mychef-seo/content/_locations_*.md and _private-chef_*.md files into the myCHEF system.

For every location/private-chef content file:
  - Convert the FULL REPLACEMENT CONTENT section to HTML
  - Apply resolved business blocker rules
  - Store the HTML in src/data/content/articleContent.ts keyed by route path
  - Patch PrivateChefAreaPage.tsx to render ArticleContentSection
  - Patch individual location pages to render ArticleContentSection

Run: python3 scripts/publish-location-private-chef-content.py
"""

import csv
import json
import re
from pathlib import Path
import markdown

REPO = Path(__file__).resolve().parent.parent
SEO = Path("/Users/openclaw/Movies/LIve website/mychef-seo")
CSV_PATH = SEO / "10-metadata-map.csv"
CONTENT_DIR = SEO / "content"
ARTICLE_CONTENT_PATH = REPO / "src/data/content/articleContent.ts"
PRIVATE_CHEF_PAGE_PATH = REPO / "src/components/PrivateChefAreaPage.tsx"
PAGES_DIR = REPO / "src/pages"

# Map content filename to canonical route
ROUTE_FOR_FILE = {
    "_locations_canggu.md": "/locations/canggu",
    "_locations_jakarta.md": "/locations/jakarta",
    "_locations_jimbaran.md": "/locations/jimbaran",
    "_locations_nusa-dua.md": "/locations/nusa-dua",
    "_locations_pererenan.md": "/locations/pererenan",
    "_locations_sanur.md": "/locations/sanur",
    "_locations_seminyak.md": "/locations/seminyak",
    "_locations_ubud.md": "/locations/ubud",
    "_locations_uluwatu.md": "/locations/uluwatu",
    "_private-chef_canggu.md": "/private-chef/canggu",
    "_private-chef_jimbaran.md": "/private-chef/jimbaran",
    "_private-chef_nusa-dua.md": "/private-chef/nusa-dua",
    "_private-chef_pererenan.md": "/private-chef/pererenan",
    "_private-chef_sanur.md": "/private-chef/sanur",
    "_private-chef_seminyak.md": "/private-chef/seminyak",
    "_private-chef_ubud.md": "/private-chef/ubud",
    "_private-chef_uluwatu.md": "/private-chef/uluwatu",
}

# Map route to location page component filename
LOCATION_PAGE_FOR_ROUTE = {
    "/locations/canggu": "CangguPage.tsx",
    "/locations/jakarta": "JakartaPage.tsx",
    "/locations/jimbaran": "JimbaranPage.tsx",
    "/locations/nusa-dua": "NusaDuaPage.tsx",
    "/locations/pererenan": "PererenanPage.tsx",
    "/locations/sanur": "SanurPage.tsx",
    "/locations/seminyak": "SeminyakPage.tsx",
    "/locations/ubud": "UbudPage.tsx",
    "/locations/uluwatu": "UluwatuPage.tsx",
}


def parse_metadata_map(path: Path) -> dict[str, dict]:
    rows = {}
    with path.open(encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            url = (row.get("url") or "").strip()
            if not url:
                continue
            rows[url] = {
                "title": (row.get("recommended_title") or "").strip(),
                "description": (row.get("recommended_meta") or "").strip(),
                "h1": (row.get("recommended_h1") or "").strip(),
            }
    return rows


def extract_replacement_content(text: str) -> str:
    """Return the publishable markdown after the FULL REPLACEMENT CONTENT marker."""
    markers = [
        r"##\s+FULL REPLACEMENT CONTENT",
        r"#\s+FULL REPLACEMENT CONTENT",
        r"##\s+2\.\s*FULL REPLACEMENT CONTENT",
    ]
    for marker in markers:
        m = re.search(marker, text, re.IGNORECASE)
        if m:
            return text[m.end():].strip()
    parts = re.split(r"\n---\s*\n", text, maxsplit=2)
    if len(parts) >= 2:
        return parts[-1].strip()
    return text.strip()


def md_to_html(text: str) -> str:
    md = markdown.Markdown(extensions=["tables", "fenced_code", "toc"])
    return md.convert(text)


def read_article_content(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.search(
        r"export const ARTICLE_CONTENT: Record<string, string> = (\{.*\})\n",
        text,
        re.DOTALL,
    )
    if not m:
        return {}
    data: dict[str, str] = {}
    for km in re.finditer(r'"([^"]+)"\s*:\s*"((?:[^"\\]|\\.)*)"', m.group(1)):
        data[km.group(1)] = json.loads('"' + km.group(2) + '"')
    return data


def serialize_article_content(data: dict[str, str]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/publish-content.py — edit source markdown, not this file.\n",
        "/** Full article HTML bodies, keyed by route path. Imported ONLY by the lazy",
        " *  article renderer and the build-time inject-meta step — never the eager nav bundle. */",
        "export const ARTICLE_CONTENT: Record<string, string> = {",
    ]
    for i, (key, value) in enumerate(sorted(data.items())):
        comma = "," if i < len(data) - 1 else ""
        lines.append(f'  "{key}": {json.dumps(value, ensure_ascii=False)}{comma}')
    lines.append("}\n")
    return "\n".join(lines)


def apply_business_blockers(html: str, route: str = "") -> str:
    """Apply the resolved business-blocker facts and strip unresolved placeholders."""
    # Deposit: wherever a deposit is mentioned, it is 50%.
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*deposit[^\]]*\]",
        "A 50% deposit confirms your date",
        html,
        flags=re.IGNORECASE,
    )
    # Founding year: 2019
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*(?:found|established|since)[^\]]*\]",
        "2019",
        html,
        flags=re.IGNORECASE,
    )
    # Villa chef half-day 2M / full-day 4M
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*villa chef[^\]]*\]",
        "Villa chef service starts from IDR 2,000,000 for a half-day and IDR 4,000,000 for a full day",
        html,
        flags=re.IGNORECASE,
    )
    # Corporate minimum spend IDR 50,000,000
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*corporate[^\]]*minimum[^\]]*\]",
        "Corporate events have a minimum spend of IDR 50,000,000",
        html,
        flags=re.IGNORECASE,
    )
    # Placement fee hidden
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*placement fee[^\]]*\]",
        "Placement fees are discussed once we understand the role and candidate requirements",
        html,
        flags=re.IGNORECASE,
    )
    # Generic from-price / approve / worked example placeholders
    html = re.sub(
        r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*(?:from-price|approve|worked example|recurring contract)[^\]]*\]",
        "Contact us for current pricing",
        html,
        flags=re.IGNORECASE,
    )
    # Strip any remaining generic placeholders
    html = re.sub(r"\[BUSINESS CONFIRMATION REQUIRED[^\]]*\]", "", html, flags=re.IGNORECASE)
    # Normalize whitespace left by removed placeholders
    html = re.sub(r"\n{3,}", "\n\n", html)
    html = re.sub(r"  +", " ", html)
    return html


def patch_private_chef_page(path: Path) -> None:
    """Add ArticleContentSection import and render it in PrivateChefAreaPage."""
    text = path.read_text(encoding="utf-8")
    if "ArticleContentSection" in text:
        return

    # Add import from shared if not present
    import_line = "import { ArticleContentSection } from '@/components/shared'"
    if import_line.split("from")[0].strip() not in text:
        last_import = text.rfind("import ")
        if last_import != -1:
            end = text.index("\n", last_import) + 1
            text = text[:end] + import_line + "\n" + text[end:]
        else:
            text = import_line + "\n" + text

    # Add ArticleContentSection near the end before closing div
    if "<StickyMobileCTA" in text:
        text = text.replace(
            "<StickyMobileCTA",
            "<ArticleContentSection />\n      <StickyMobileCTA",
        )
    else:
        # Fallback: insert before the final "</div>" in the return
        text = re.sub(
            r"(\n)(\s*)</div>\n(\s*)\)\n\}$",
            r"\1\2<ArticleContentSection />\n\2</div>\n\3)\n}",
            text,
            count=1,
        )

    path.write_text(text, encoding="utf-8")


def patch_location_page(path: Path) -> None:
    """Add ArticleContentSection import and render it in a location page."""
    text = path.read_text(encoding="utf-8")
    if "ArticleContentSection" in text:
        return

    # Add import
    import_line = "import { ArticleContentSection } from '@/components/shared'"
    if import_line.split("from")[0].strip() not in text:
        last_import = text.rfind("import ")
        if last_import != -1:
            end = text.index("\n", last_import) + 1
            text = text[:end] + import_line + "\n" + text[end:]
        else:
            text = import_line + "\n" + text

    # Insert before final "</div>" in the component return
    text = re.sub(
        r"(\n)(\s*)</div>\n(\s*)\)\n\}$",
        r"\1\2<ArticleContentSection />\n\2</div>\n\3)\n}",
        text,
        count=1,
    )

    path.write_text(text, encoding="utf-8")


def main():
    metadata = parse_metadata_map(CSV_PATH)
    article_content = read_article_content(ARTICLE_CONTENT_PATH)

    updated = 0
    skipped = 0

    for filename, route in sorted(ROUTE_FOR_FILE.items()):
        md_path = CONTENT_DIR / filename
        if not md_path.exists():
            skipped += 1
            print(f"SKIP (missing): {filename}")
            continue

        md_text = md_path.read_text(encoding="utf-8")
        replacement_md = extract_replacement_content(md_text)
        if not replacement_md:
            skipped += 1
            print(f"SKIP (empty): {filename}")
            continue

        html = md_to_html(replacement_md)
        html = apply_business_blockers(html, route)
        article_content[route] = html
        updated += 1
        print(f"PUBLISHED: {route} ({len(html)} chars HTML)")

    ARTICLE_CONTENT_PATH.write_text(
        serialize_article_content(article_content), encoding="utf-8"
    )

    # Patch PrivateChefAreaPage to render article content
    patch_private_chef_page(PRIVATE_CHEF_PAGE_PATH)
    print("PATCHED: src/components/PrivateChefAreaPage.tsx")

    # Patch location pages
    patched_locations = 0
    for route, page_file in LOCATION_PAGE_FOR_ROUTE.items():
        page_path = PAGES_DIR / page_file
        if not page_path.exists():
            print(f"SKIP location page (missing): {page_file}")
            continue
        patch_location_page(page_path)
        patched_locations += 1
        print(f"PATCHED: {page_file}")

    print(f"\nDone. Updated {updated} article entries, skipped {skipped}.")
    print(f"Patched {patched_locations} location pages + PrivateChefAreaPage.")


if __name__ == "__main__":
    main()
