#!/usr/bin/env python3
"""
Publish remaining mychef-seo/content/*.md files that are not in landingPages.ts
but are wired to dedicated React routes (locations, private-chef areas, etc.).

Adds their FULL REPLACEMENT CONTENT as HTML into articleContent.ts keyed by route path.
"""

import re
import json
from pathlib import Path
import markdown

REPO = Path(__file__).resolve().parent.parent
SEO = Path("/Users/openclaw/Movies/LIve website/mychef-seo")
CONTENT_DIR = SEO / "content"
ARTICLE_CONTENT_PATH = REPO / "src/data/content/articleContent.ts"

# Mapping from content filename stem to route path
# BALI-ONLY: do not re-add Jakarta/Menteng entries (e.g. "_locations_jakarta") — the site is Bali-only.
ROUTE_MAP = {
    "_locations_canggu": "/locations/canggu",
    "_locations_jimbaran": "/locations/jimbaran",
    "_locations_nusa-dua": "/locations/nusa-dua",
    "_locations_pererenan": "/locations/pererenan",
    "_locations_sanur": "/locations/sanur",
    "_locations_seminyak": "/locations/seminyak",
    "_locations_ubud": "/locations/ubud",
    "_locations_uluwatu": "/locations/uluwatu",
    "_private-chef_canggu": "/private-chef/canggu",
    "_private-chef_jimbaran": "/private-chef/jimbaran",
    "_private-chef_nusa-dua": "/private-chef/nusa-dua",
    "_private-chef_pererenan": "/private-chef/pererenan",
    "_private-chef_sanur": "/private-chef/sanur",
    "_private-chef_seminyak": "/private-chef/seminyak",
    "_private-chef_ubud": "/private-chef/ubud",
    "_private-chef_uluwatu": "/private-chef/uluwatu",
    "home": "/",
}


def extract_replacement_content(text: str) -> str:
    markers = [
        r"##\s+FULL REPLACEMENT CONTENT",
        r"#\s+FULL REPLACEMENT CONTENT",
        r"##\s+2\.\s*FULL REPLACEMENT CONTENT",
    ]
    for marker in markers:
        m = re.search(marker, text, re.IGNORECASE)
        if m:
            content = text[m.end():]
            content = re.split(r"\n---\s*\n", content, maxsplit=1)[0]
            content = re.sub(r"\*\*Title tag:\*\*.*?\n", "", content)
            content = re.sub(r"\*\*Meta description:\*\*.*?\n", "", content)
            return content.strip()
    parts = re.split(r"\n---\s*\n", text, maxsplit=2)
    if len(parts) >= 2:
        return parts[-1].strip()
    return text.strip()


def read_article_content(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.search(r"export const ARTICLE_CONTENT: Record<string, string> = (\{.*\})\n", text, re.DOTALL)
    if not m:
        return {}
    data: dict[str, str] = {}
    for km in re.finditer(r'"([^"]+)"\s*:\s*"((?:[^"\\]|\\.)*)"', m.group(1)):
        data[km.group(1)] = json.loads('"' + km.group(2) + '"')
    return data


def serialize_article_content(data: dict[str, str]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/publish-content.py — edit source markdown, not this file.\n",
        "/** Full article HTML bodies, keyed by route path. Imported ONLY by the lazy",
        " *  article renderer and the build-time inject-meta step — never the eager nav bundle. */",
        "export const ARTICLE_CONTENT: Record<string, string> = {",
    ]
    for i, (key, value) in enumerate(sorted(data.items())):
        comma = "," if i < len(data) - 1 else ""
        lines.append(f'  "{key}": {json.dumps(value, ensure_ascii=False)}{comma}')
    lines.append("}\n")
    return "\n".join(lines)


def main():
    article_content = read_article_content(ARTICLE_CONTENT_PATH)
    updated = 0
    skipped = 0

    for stem, route in ROUTE_MAP.items():
        md_path = CONTENT_DIR / f"{stem}.md"
        if not md_path.exists():
            print(f"SKIP (missing file): {stem}")
            skipped += 1
            continue

        md_text = md_path.read_text(encoding="utf-8")
        replacement_md = extract_replacement_content(md_text)
        html = markdown.markdown(replacement_md, extensions=["tables", "fenced_code", "toc"])

        if route in article_content:
            print(f"OVERWRITE: {stem} → {route} ({len(html)} chars)")
        else:
            print(f"ADD: {stem} → {route} ({len(html)} chars)")
        article_content[route] = html
        updated += 1

    ARTICLE_CONTENT_PATH.write_text(serialize_article_content(article_content), encoding="utf-8")
    print(f"\nDone. Updated {updated} article entries, skipped {skipped}.")


if __name__ == "__main__":
    main()
