#!/usr/bin/env python3
"""Update articleContent.ts for staffing pages from mychef-seo/content markdown."""

from pathlib import Path
import json
import re
import markdown

REPO = Path(__file__).resolve().parent.parent
SEO = Path("/Users/openclaw/Movies/LIve website/mychef-seo")
ARTICLE_CONTENT_PATH = REPO / "src/data/content/articleContent.ts"

STAFFING_FILES = {
    "staffing.md": "/staffing",
    "staffing_private-chef-placement.md": "/staffing/private-chef-placement",
    "staffing_live-in-chef.md": "/staffing/live-in-chef",
    "staffing_villa-staff.md": "/staffing/villa-staff",
    "staffing_household-staff.md": "/staffing/household-staff",
    "staffing_for-villa-managers.md": "/staffing/for-villa-managers",
    "staffing_for-hotels-restaurants.md": "/staffing/for-hotels-restaurants",
    "villa-staff-bali-agency.md": "/villa-staff-bali-agency",
}


def extract_replacement_content(text: str) -> str:
    markers = [
        r"##\s+FULL REPLACEMENT CONTENT",
        r"#\s+FULL REPLACEMENT CONTENT",
        r"##\s+2\.\s*FULL REPLACEMENT CONTENT",
    ]
    for marker in markers:
        m = re.search(marker, text, re.IGNORECASE)
        if m:
            content = text[m.end():]
            content = re.split(r"\n---\s*\n", content, maxsplit=1)[0]
            return content.strip()
    parts = re.split(r"\n---\s*\n", text, maxsplit=2)
    if len(parts) >= 2:
        return parts[-1].strip()
    return text.strip()


def read_article_content(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.search(r"export const ARTICLE_CONTENT: Record<string, string> = (\{.*\})\n", text, re.DOTALL)
    if not m:
        return {}
    data: dict[str, str] = {}
    for km in re.finditer(r'"([^"]+)"\s*:\s*"((?:[^"\\]|\\.)*)"', m.group(1)):
        data[km.group(1)] = json.loads('"' + km.group(2) + '"')
    return data


def serialize_article_content(data: dict[str, str]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/publish-content.py — edit source markdown, not this file.\n",
        "/** Full article HTML bodies, keyed by route path. Imported ONLY by the lazy",
        " *  article renderer and the build-time inject-meta step — never the eager nav bundle. */",
        "export const ARTICLE_CONTENT: Record<string, string> = {",
    ]
    for i, (key, value) in enumerate(sorted(data.items())):
        comma = "," if i < len(data) - 1 else ""
        lines.append(f'  "{key}": {json.dumps(value, ensure_ascii=False)}{comma}')
    lines.append("}\n")
    return "\n".join(lines)


def main():
    article_content = read_article_content(ARTICLE_CONTENT_PATH)
    md = markdown.Markdown(extensions=["tables", "fenced_code", "toc"])

    for fname, path in STAFFING_FILES.items():
        md_path = SEO / "content" / fname
        if not md_path.exists():
            print(f"Skip (missing): {fname}")
            continue
        text = md_path.read_text(encoding="utf-8")
        replacement = extract_replacement_content(text)
        html = md.convert(replacement)
        md.reset()
        article_content[path] = html
        print(f"Updated: {path} ({len(html)} chars)")

    ARTICLE_CONTENT_PATH.write_text(serialize_article_content(article_content), encoding="utf-8")
    print("\nDone. articleContent.ts updated.")


if __name__ == "__main__":
    main()
