// AUTO-GENERATED by scripts/gen-split-content.ts — edit the split source, not a merged copy.
import type { ContentEntry } from '@/lib/blog'

export const BLOG_POSTS: ContentEntry[] = [
  {
    "slug": "blog/private-chef-cost-bali",
    "title": "How Much Does a Private Chef in Bali Cost? [2026 Guide]",
    "description": "Private chef costs in Bali range from IDR 1M++/day for villa chef hire (chef + assistant) to IDR 20M+ for large events. Real 2026 pricing, what is included, and how to book.",
    "date": "2025-01-15"
  },
  {
    "slug": "blog/private-chef-bali-cost-breakdown-2026",
    "title": "Private Chef Bali Cost Breakdown 2026",
    "description": "2026 Bali private chef cost breakdown with sample villa dinner totals and grocery ranges.",
    "date": "2026-05-10"
  },
  {
    "slug": "blog/best-bali-villas-private-chef-kitchen",
    "title": "What Makes a Bali Villa Kitchen Work for a Private Chef",
    "description": "What private chefs need in a Bali villa kitchen — prep space, equipment, ventilation, cold storage — and how to check before booking.",
    "date": "2026-04-24"
  },
  {
    "slug": "blog/wedding-rehearsal-dinner-bali",
    "title": "Wedding Rehearsal Dinner in Bali",
    "description": "How to plan a stress-free rehearsal dinner in your villa before the big day.",
    "date": "2026-04-08"
  },
  {
    "slug": "blog/yoga-retreat-chef-bali-meal-planning",
    "title": "Yoga Retreat Chef Bali | Meal Planning",
    "description": "Structuring nutrient-dense, plant-forward menus for multi-day wellness retreats.",
    "date": "2026-03-21"
  },
  {
    "slug": "blog/private-chef-vs-restaurant-bali",
    "title": "Private Chef vs Restaurant Bali: Which Is Actually Better",
    "description": "Private chef or restaurant in Bali? Full cost comparison, menu control, and comfort breakdown for groups, families, and villa stays. Find out which wins.",
    "date": "2026-03-05"
  },
  {
    "slug": "blog/how-to-plan-villa-birthday-party-bali",
    "title": "How to Plan a Villa Birthday Party in Bali: The Complete",
    "description": "Step-by-step guide to planning a villa birthday party in Bali — from catering formats and guest counts to timelines, styling, and private chef logistics.",
    "date": "2026-05-10"
  },
  {
    "slug": "blog/private-chef-romantic-dinners-bali",
    "title": "Private Chef Romantic Dinners in Bali: How to Plan the",
    "description": "How to plan a romantic private chef dinner in your Bali villa — menu styles, timing, proposal setups, anniversaries & what makes the evening work.",
    "date": "2026-05-10"
  },
  {
    "slug": "blog/how-to-hire-private-chef-bali-complete-guide",
    "title": "Complete Guide: How to Hire a Private Chef in Bali",
    "description": "Step-by-step guide to hiring a private chef in Bali with tips on qualifications, vetting, costs, and the hiring process.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/chef-qualifications-credentials-bali-hiring",
    "title": "Chef Qualifications & Credentials: Hiring Guide for Bali",
    "description": "Essential qualifications, certifications, and experience markers for hiring a qualified private chef in Bali.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/fine-dining-guide",
    "title": "Fine Dining in Bali: Ultimate Guide to Private Chef Tasting",
    "description": "Discover fine dining in Bali with private chefs. Curated tasting menus, wine pairings, and luxury culinary experiences for villa stays.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/private-chef-roles-responsibilities-explained",
    "title": "Understanding Private Chef Roles & Responsibilities",
    "description": "Clarity on what private chefs do, how they differ from other culinary professionals, and what to expect when you hire one.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/wedding-private-chef-bali-planning-guide",
    "title": "Wedding Private Chef in Bali: Planning & Logistics Guide",
    "description": "How to plan catering for a Bali villa wedding with a private chef, including menu planning, logistics, and cost expectations.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/corporate-events-catering-bali-team-dining",
    "title": "Corporate Events & Team Dining in Bali: Private Chef",
    "description": "How to plan corporate events, team meals, and executive dinners in Bali with private chef catering.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/romantic-dinner-at-home-bali-private-chef",
    "title": "Romantic Dinner at Home: Private Chef Experiences in Bali",
    "description": "How to plan an intimate, memorable romantic dinner with a private chef in your Bali villa or home.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/dining-by-location-bali-neighborhood-guide",
    "title": "Dining by Location in Bali: Private Chef Experiences by",
    "description": "Region-specific dining guide for Bali, including neighborhood profiles and how private chefs adapt to each area.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/fine-dining-trends-bali-2026-innovations",
    "title": "Fine Dining Trends in Bali 2026: Modern Innovations &",
    "description": "Emerging culinary trends in Bali for 2026, including sustainability, technique innovation, and what sophisticated diners expect.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/seasonal-ingredients-bali-cooking-guide",
    "title": "Seasonal Ingredients in Bali: Cooking & Sourcing Guide for",
    "description": "Complete guide to Bali seasonal ingredients, what is available when, and how to plan menus around the seasons.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/private-chef-breakfast-bali-villas",
    "title": "Private Chef Breakfast in Bali Villas: Plan Before Day One",
    "description": "Plan a private chef breakfast in Bali before you land, with menu ideas, kitchen checks, staffing tips, and realistic timing for villa stays.",
    "date": "2026-05-17"
  },
  {
    "slug": "blog/birthday-dinner-bali-villa-without-planner",
    "title": "Birthday Dinner Bali Villa: Plan It Without a Full Planner",
    "description": "Plan a birthday dinner in a Bali villa without a full planner, with food formats, staffing math, timing, and a simple host run sheet.",
    "date": "2026-05-17"
  },
  {
    "slug": "blog/seminyak-canggu-ubud-uluwatu-private-chef-night",
    "title": "Seminyak, Canggu, Ubud or Uluwatu for a Private Chef Night?",
    "description": "Compare Seminyak, Canggu, Ubud, and Uluwatu for a private chef night, from traffic and sunset timing to menu style and villa flow.",
    "date": "2026-05-17"
  },
  {
    "slug": "blog/private-chef-bali-preparation-12-guest-villa-dinner",
    "title": "Private Chef Bali Preparation: Behind a 12-Guest Villa",
    "description": "See how myCHEF prepares a 12-guest villa dinner in Bali, from market runs and packing lists to service timing, plating, and cleanup.",
    "date": "2026-05-17"
  },
  {
    "slug": "blog/family-kids-menu-private-chef-bali",
    "title": "Family Dining with a Private Chef in Bali: A Parent's Guide",
    "description": "Planning villa dining for a family in Bali? Our chefs build kids' menus around ages and preferences. No restaurant stress. Book in 24 hours.",
    "date": "2026-04-10"
  },
  {
    "slug": "blog/corporate-events-catering-bali",
    "title": "Corporate Event Catering in Bali: 4 Real Case Studies (2025)",
    "description": "How myCHEF handled a 38-person tech retreat, bank executive dinner, fashion launch, and 7-day wellness retreat in Bali. Real costs, menus & outcomes.",
    "date": "2026-04-25"
  },
  {
    "slug": "blog/food-allergies-dietary-requirements-private-chef-bali",
    "title": "Food Allergies & Dietary Requirements in Bali: Safety Guide",
    "description": "How myCHEF handles food allergies and special diets in Bali: HACCP protocols, cross-contamination controls, and custom menus for vegan, gluten-free, halal.",
    "date": "2026-04-20"
  },
  {
    "slug": "blog/how-to-hire-private-chef",
    "title": "How to Hire a Private Chef in Bali: Complete Guide",
    "description": "Step-by-step guide to hiring a private chef in Bali. What to look for, how to vet candidates, costs, and the full hiring process.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/chef-hiring-guide",
    "title": "How to Hire a Private Chef in Bali: Quick-Start Guide",
    "description": "Hire the right private chef in Bali. Learn what credentials to check, how to interview, key questions, and red flags when vetting a chef.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/event-planning-bali",
    "title": "Event Planning in Bali: Weddings & Celebrations Guide",
    "description": "Complete Bali event planning guide. Catering, staffing, venue setup, and timeline for weddings, corporate events, and celebrations.",
    "date": "2026-05-18"
  },
  {
    "slug": "blog/bali-wedding-catering-private-chef-timeline",
    "title": "Bali Wedding Catering Private Chef Timeline: 6-Month",
    "description": "The complete Bali wedding catering timeline — what to book, when to confirm, and how chefs coordinate with venues, planners and your event schedule.",
    "date": "2026-06-26"
  },
  {
    "slug": "blog/bali-catering-menu",
    "title": "Bali Catering Menus: Traditional & Modern Options for Your",
    "description": "Explore Bali catering menus — traditional Indonesian, modern fusion, plated dinners, buffets, and grazing boards for villa events.",
    "date": "2026-05-18"
  }
]
