// AUTO-GENERATED by scripts/gen-split-content.ts — edit the split source, not a merged copy.
import type { ContentEntry } from '@/lib/blog'

export const GUIDES: ContentEntry[] = [
  {
    "slug": "guide/bali-cuisine-glossary",
    "title": "Bali Cuisine Glossary",
    "description": "A complete glossary of Balinese cuisine — ingredients, dishes, and cooking techniques.",
    "date": "2025-01-15"
  },
  {
    "slug": "guide/private-chef-bali",
    "title": "Private Chef in Bali — Complete Guide",
    "description": "Everything you need to know about hiring a private chef in Bali — costs and expectations.",
    "date": "2025-02-01"
  }
]
