// AUTO-GENERATED by scripts/gen-split-content.ts — edit the split source, not a merged copy.
import type { ContentEntry } from '@/lib/blog'

export const GUIDES: ContentEntry[] = [
  {
    "slug": "guide/bali-cuisine-glossary",
    "title": "Bali Cuisine Glossary — Balinese Ingredients, Dishes & Techniques",
    "description": "A complete glossary of Balinese cuisine — ingredients, dishes, and cooking techniques.",
    "date": "2025-01-15"
  },
  {
    "slug": "guide/private-chef-bali",
    "title": "Private Chef Bali Areas | Coverage Map by Villa Region",
    "description": "myCHEF private chef coverage across Bali’s top villa regions — Seminyak, Canggu, Ubud, Uluwatu, Sanur, Nusa Dua, Jimbaran and more.",
    "date": "2025-02-01"
  }
]
