// AUTO-GENERATED by scripts/gen-split-content.ts — edit the split source, not a merged copy.
import type { JournalPost } from '@/data/siteArchitecture'

export const JOURNAL_POSTS: JournalPost[] = [
  {
    "slug": "michelin-training-bali",
    "title": "Michelin Training in Bali: How Our Chefs Master Italian Technique",
    "category": "recipes",
    "author": "Adriano",
    "date": "2026-05-10",
    "readTime": 7,
    "excerpt": "Discover how Michelin-trained techniques translate to intimate villa dining in Bali."
  },
  {
    "slug": "sustainable-sourcing",
    "title": "Sustainable Sourcing: Our Farm-to-Villa Philosophy",
    "category": "wellness",
    "author": "myCHEF Team",
    "date": "2026-05-05",
    "readTime": 6,
    "excerpt": "Learn about our commitment to local, organic ingredients and the Bali producers we work with directly."
  },
  {
    "slug": "private-chef-vs-villa-staff-bali",
    "title": "Private Chef vs. Villa Staff: Understanding the Difference in Bali",
    "category": "travel",
    "author": "myCHEF Team",
    "date": "2026-05-17",
    "readTime": 6,
    "excerpt": "Why hiring a specialized private chef beats relying on general villa staff for your milestone dinner."
  },
  {
    "slug": "bali-private-chef-cost-guide-2026",
    "title": "The 2026 Bali Private Chef Cost Guide: Menus, Groceries, and Tips",
    "category": "travel",
    "author": "Adriano",
    "date": "2026-05-17",
    "readTime": 8,
    "excerpt": "A transparent breakdown of what to expect when booking a private chef in Bali this year."
  },
  {
    "slug": "villa-wedding-catering-logistics-bali",
    "title": "Villa Wedding Catering Logistics Guide for Bali",
    "category": "events",
    "author": "myCHEF Team",
    "date": "2026-05-17",
    "readTime": 10,
    "excerpt": "From kitchen requirements to service flow, here is what you need to know for your villa wedding."
  },
  {
    "slug": "yoga-retreat-meal-planning-bali",
    "title": "Yoga Retreat Meal Planning: Nutritional Integrity for Bali Retreats",
    "category": "wellness",
    "author": "myCHEF Team",
    "date": "2026-05-17",
    "readTime": 7,
    "excerpt": "How we design retreat menus that balance detoxification with culinary satisfaction."
  },
  {
    "slug": "private-chef-seminyak-guide",
    "title": "Hiring a Private Chef in Seminyak: The 2026 Local's Guide",
    "category": "travel",
    "author": "myCHEF Team",
    "date": "2026-05-18",
    "readTime": 8,
    "excerpt": "Everything you need to know about booking a private chef for your Seminyak villa stay—from pricing to logistics."
  },
  {
    "slug": "private-chef-canggu-guide",
    "title": "Private Chef Services in Canggu: What Makes It Different",
    "category": "travel",
    "author": "Adriano",
    "date": "2026-05-18",
    "readTime": 7,
    "excerpt": "Why Canggu's laid-back surf culture creates unique opportunities for villa dining experiences."
  },
  {
    "slug": "private-chef-ubud-villa-dining",
    "title": "Private Chef Services in Ubud: Logistics, Pricing & What to Expect",
    "category": "travel",
    "author": "myCHEF Team",
    "date": "2026-05-18",
    "readTime": 8,
    "excerpt": "The complete guide to hiring a private chef for your Ubud villa—from jungle logistics to cultural dining experiences."
  },
  {
    "slug": "bali-wedding-catering-complete-guide",
    "title": "Bali Wedding Catering Guide: Budgets, Logistics & Vendors",
    "category": "events",
    "author": "Adriano",
    "date": "2026-05-18",
    "readTime": 10,
    "excerpt": "Everything you need to know about catering a destination wedding in Bali—from menu design to cultural considerations."
  },
  {
    "slug": "private-chef-jakarta-guide",
    "title": "Private Chef Services in Jakarta: What to Expect in 2026",
    "category": "travel",
    "author": "myCHEF Team",
    "date": "2026-05-20",
    "readTime": 9,
    "excerpt": "The complete guide to hiring a private chef in Jakarta—from Menteng estates to SCBD boardrooms."
  },
  {
    "slug": "rehearsal-dinner-planning-bali",
    "title": "Planning Your Bali Rehearsal Dinner: The Complete Guide",
    "category": "events",
    "author": "Adriano",
    "date": "2026-05-20",
    "readTime": 7,
    "excerpt": "Everything you need to know about planning an unforgettable rehearsal dinner in Bali—from villa selection to menu design."
  },
  {
    "slug": "live-in-chef-vs-daily-service",
    "title": "Live-In Chef vs. Daily Service: Which is Right for Your Bali Villa?",
    "category": "travel",
    "author": "myCHEF Team",
    "date": "2026-05-20",
    "readTime": 8,
    "excerpt": "A transparent comparison of live-in chef services vs. on-demand daily bookings for long-stay villa guests."
  },
  {
    "slug": "bbq-catering-cost-breakdown-bali",
    "title": "BBQ Catering in Bali: The Complete Cost Breakdown",
    "category": "travel",
    "author": "myCHEF Team",
    "date": "2026-05-20",
    "readTime": 7,
    "excerpt": "Transparent pricing for villa BBQ catering in Bali—from budget feasts to premium Wagyu experiences."
  }
]
