// AUTO-GENERATED by scripts/gen-split-content.ts — edit the split source, not a merged copy.
import type { ContentEntry } from '@/lib/blog'

export const LANDING_PAGES: ContentEntry[] = [
  {
    "slug": "villa-bbq-catering-bali",
    "title": "Villa BBQ Catering Bali | In-Villa BBQ Party Packages",
    "description": "In-villa BBQ party packages in Bali: chef, grill, setup & cleanup at your villa poolside. Packages for 6-80 guests with per-pax pricing. WhatsApp myCHEF.",
    "date": "2026-05-17"
  },
  {
    "slug": "bali-wedding-catering-packages",
    "title": "Bali Wedding Catering Packages & Prices 2026",
    "description": "Transparent Bali wedding catering packages: plated, buffet & cocktail reception pricing by guest count for private villa weddings. WhatsApp myCHEF.",
    "date": "2026-05-17"
  },
  {
    "slug": "michelin-private-chef-bali-prices",
    "title": "Michelin Private Chef Bali Prices | 2026 Cost Guide",
    "description": "Transparent pricing for Michelin-standard private chef experiences in Bali. Cost breakdowns for menus and groceries.",
    "date": "2026-05-17"
  },
  {
    "slug": "private-tasting-menu-bali",
    "title": "Private Tasting Menu Bali | Michelin-Standard Villa Dining",
    "description": "Experience 7-11 course private tasting menus in your Bali villa. Italian technique met with Balinese ingredients.",
    "date": "2026-05-17"
  },
  {
    "slug": "chef-table-experience-bali",
    "title": "Chef Table Experience Bali | Interactive Fine Dining",
    "description": "An interactive, counter-side private dining experience. Watch our Michelin-trained chefs work course-by-course.",
    "date": "2026-05-17"
  },
  {
    "slug": "seafood-bbq-catering-bali",
    "title": "Seafood BBQ Bali | Market-Fresh Grill at Your Villa | myCHEF",
    "description": "Fresh seafood BBQs for Bali villas: snapper, prawns, lobster grilled live poolside, sourced direct from Jimbaran market. WhatsApp myCHEF.",
    "date": "2026-05-17"
  },
  {
    "slug": "group-villa-dinner-packages-bali",
    "title": "Group Villa Dinner Packages Bali | Easy Booking for 10-150 Guests",
    "description": "All-inclusive villa dinner packages for large groups in Bali. Perfect for family reunions and social gatherings.",
    "date": "2026-05-17"
  },
  {
    "slug": "corporate-retreat-catering-bali",
    "title": "Corporate Retreat Catering Bali | Offsite Meal Programs",
    "description": "Multi-day catering for corporate retreats & offsites in Bali: full-day meal structures, NPWP invoices, executive service. WhatsApp myCHEF.",
    "date": "2026-05-17"
  },
  {
    "slug": "luxury-birthday-party-bali",
    "title": "Luxury Birthday Party Bali | Milestone Celebrations | myCHEF",
    "description": "Luxury milestone birthday parties in Bali: private chef, premium menus, drinks & styling for 30th/40th/50th celebrations. WhatsApp myCHEF.",
    "date": "2026-05-17"
  },
  {
    "slug": "hire-private-chef-bali-monthly",
    "title": "Hire Private Chef Bali Monthly | Long-Stay Villa Hosting",
    "description": "Monthly and long-term private chef placements for Bali villas and residences. Vetted, professional culinary teams.",
    "date": "2026-05-17"
  },
  {
    "slug": "villa-staff-bali-agency",
    "title": "Villa Staff Placement Has Moved",
    "h1": "Looking for a Villa Staff Agency in Bali?",
    "description": "Our villa staff agency services now live on one page: vetted long-term villa staff placement in Bali — managers, housekeepers, chefs. See myCHEF.",
    "date": "2026-05-17",
    "jsonLd": [
      {
        "@context": "https://schema.org",
        "@graph": [
          {
            "@type": "WebPage",
            "@id": "https://mychef.id/villa-staff-bali-agency",
            "name": "Villa Staff Placement Has Moved | myCHEF Bali",
            "description": "myCHEF's villa staff agency services now live on the villa staff placement page: vetted long-term villa staff for Bali villas and estates.",
            "isPartOf": { "@type": "WebSite", "name": "myCHEF", "url": "https://mychef.id" },
            "about": {
              "@type": "Organization",
              "name": "myCHEF",
              "url": "https://mychef.id",
              "telephone": "+62 896-7407-2020"
            },
            "mainEntity": { "@id": "https://mychef.id/staffing/villa-staff" }
          },
          {
            "@type": "BreadcrumbList",
            "itemListElement": [
              { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://mychef.id/" },
              { "@type": "ListItem", "position": 2, "name": "Villa Staff Bali Agency", "item": "https://mychef.id/villa-staff-bali-agency" }
            ]
          }
        ]
      }
    ]
  },
  {
    "slug": "butler-service-bali-daily-rate",
    "title": "Butler Service Bali Daily Rate | Professional Villa Hosting",
    "description": "Hire professional, English-speaking butlers in Bali by the day or shift. Discreet and anticipatory guest service.",
    "date": "2026-05-17"
  },
  {
    "slug": "best-private-chef-indonesia",
    "title": "Best Private Chef Indonesia | Michelin-Standard Villa Dining",
    "description": "The premier private chef service in Indonesia. Michelin-trained leadership, local sourcing, and world-class service standards.",
    "date": "2026-05-17"
  },
  {
    "slug": "private-chef-for-events",
    "title": "Private Chef for Events Bali | Hire a Chef for Your Event",
    "description": "Hire a private chef for your Bali event — villa parties, birthdays & celebrations. Transparent chef-fee model, optional service staff. WhatsApp myCHEF.",
    "date": "2026-05-17"
  },
  {
    "slug": "luxury-chef-indonesia",
    "title": "Luxury Chef Indonesia | Premium Private Dining Experiences",
    "description": "Exclusive private chef services for high-end residences and estates in Indonesia. Discreet, professional, and refined.",
    "date": "2026-05-17"
  },
  {
    "slug": "wedding-catering-indonesia",
    "title": "Wedding Catering Indonesia | Villa Wedding Specialists",
    "description": "Premium wedding catering across Indonesia — Bali, Jakarta & beyond. Custom menus, full service teams and event coordination. WhatsApp myCHEF.",
    "date": "2026-05-17"
  },
  {
    "slug": "private-dining-indonesia",
    "title": "Private Dining Indonesia | At-Home Fine Dining Services",
    "description": "Experience at-home fine dining across Indonesia. Michelin-trained chefs, premium ingredients, and professional service.",
    "date": "2026-05-17"
  },
  {
    "slug": "healthy-meal-delivery-indonesia",
    "title": "Healthy Meal Delivery Indonesia | Chef-Prepared Villa Food",
    "description": "Gourmet healthy meal delivery and prep for Bali villas. Organic ingredients and nutrient-dense menus.",
    "date": "2026-05-17"
  },
  {
    "slug": "chef-for-hire-indonesia",
    "title": "Chef for Hire Indonesia | Private Chef Services",
    "description": "Hire a vetted private or personal chef in Indonesia for one dinner, daily villa service, recurring meals, or full-time placement in Bali.",
    "date": "2026-05-17"
  },
  {
    "slug": "proposal-dinner",
    "title": "Proposal Dinner Bali | Private Chef Proposal Experience",
    "description": "Plan the perfect proposal with a private chef dinner in your Bali villa — intimate, styled and unforgettable. Confidential planning. WhatsApp myCHEF.",
    "date": "2026-05-17"
  },
  {
    "slug": "honeymoon-chef",
    "title": "Honeymoon Private Chef Bali | Villa Dining for Couples",
    "description": "Private chef experiences for honeymooners in Bali: romantic breakfasts, sunset dinners and intimate in-villa hosting. WhatsApp myCHEF.",
    "date": "2026-05-17"
  },
  {
    "slug": "private-chef-breakfast-bali",
    "title": "Private Chef Breakfast Bali | Poolside Villa Service",
    "description": "Wake up to a chef-prepared breakfast in your Bali villa. Floating trays, fresh juices, and international spreads.",
    "date": "2026-05-17"
  },
]
