// AUTO-GENERATED by scripts/gen-split-content.ts — edit the split source, not a merged copy.
import type { ContentEntry } from '@/lib/blog'

export const LANDING_PAGES: ContentEntry[] = [
  {
    "slug": "villa-bbq-catering-bali",
    "title": "Villa BBQ Catering Bali | Best Private BBQ Experiences",
    "description": "The #1 villa BBQ catering service in Bali. Fresh grills, chef-led service, and full setup for your villa poolside party.",
    "date": "2026-05-17"
  },
  {
    "slug": "bali-wedding-catering-packages",
    "title": "Bali Wedding Catering Packages 2026 | Private Estate Weddings",
    "description": "Transparent wedding catering packages for Bali villa weddings. Plated dinners, buffets, and cocktail receptions.",
    "date": "2026-05-17"
  },
  {
    "slug": "michelin-private-chef-bali-prices",
    "title": "Michelin Private Chef Bali Prices | 2026 Cost Guide",
    "description": "Transparent pricing for Michelin-standard private chef experiences in Bali. Cost breakdowns for menus and groceries.",
    "date": "2026-05-17"
  },
  {
    "slug": "private-tasting-menu-bali",
    "title": "Private Tasting Menu Bali | Michelin-Standard Villa Dining",
    "description": "Experience 7-11 course private tasting menus in your Bali villa. Italian technique met with Balinese ingredients.",
    "date": "2026-05-17"
  },
  {
    "slug": "chef-table-experience-bali",
    "title": "Chef Table Experience Bali | Interactive Fine Dining",
    "description": "An interactive, counter-side private dining experience. Watch our Michelin-trained chefs work course-by-course.",
    "date": "2026-05-17"
  },
  {
    "slug": "seafood-bbq-catering-bali",
    "title": "Seafood BBQ Catering Bali | Direct-from-Market Freshness",
    "description": "Fresh seafood BBQs for Bali villas. Snapper, prawns, lobster, and more grilled live at your poolside.",
    "date": "2026-05-17"
  },
  {
    "slug": "group-villa-dinner-packages-bali",
    "title": "Group Villa Dinner Packages Bali | Easy Booking for 10-150 Guests",
    "description": "All-inclusive villa dinner packages for large groups in Bali. Perfect for family reunions and social gatherings.",
    "date": "2026-05-17"
  },
  {
    "slug": "corporate-retreat-catering-bali",
    "title": "Corporate Retreat Catering Bali | Professional Event Hospitality",
    "description": "Professional catering for corporate retreats and offsites in Bali. NPWP-ready invoices and executive service standards.",
    "date": "2026-05-17"
  },
  {
    "slug": "luxury-birthday-party-bali",
    "title": "Luxury Birthday Party Bali | Private Chef & Event Planning",
    "description": "Celebrate your birthday with a luxury private chef experience in Bali. We handle food, drinks, and styling.",
    "date": "2026-05-17"
  },
  {
    "slug": "hire-private-chef-bali-monthly",
    "title": "Hire Private Chef Bali Monthly | Long-Stay Villa Hosting",
    "description": "Monthly and long-term private chef placements for Bali villas and residences. Vetted, professional culinary teams.",
    "date": "2026-05-17"
  },
  {
    "slug": "villa-staff-bali-agency",
    "title": "Villa Staff Bali Agency | Professional Household Placement",
    "description": "The premier agency for villa staff in Bali. We source and vet housekeepers, butlers, and villa managers.",
    "date": "2026-05-17"
  },
  {
    "slug": "butler-service-bali-daily-rate",
    "title": "Butler Service Bali Daily Rate | Professional Villa Hosting",
    "description": "Hire professional, English-speaking butlers in Bali by the day or shift. Discreet and anticipatory guest service.",
    "date": "2026-05-17"
  },
  {
    "slug": "best-private-chef-indonesia",
    "title": "Best Private Chef Indonesia | Michelin-Standard Villa Dining",
    "description": "The premier private chef service in Indonesia. Michelin-trained leadership, local sourcing, and world-class service standards.",
    "date": "2026-05-17"
  },
  {
    "slug": "private-chef-for-events",
    "title": "Private Chef for Events | Bali Villa Party Catering",
    "description": "Hire a private chef for your next Bali villa event. From small birthdays to large celebrations, we provide the culinary team.",
    "date": "2026-05-17"
  },
  {
    "slug": "luxury-chef-indonesia",
    "title": "Luxury Chef Indonesia | Premium Private Dining Experiences",
    "description": "Exclusive private chef services for high-end residences and estates in Indonesia. Discreet, professional, and refined.",
    "date": "2026-05-17"
  },
  {
    "slug": "wedding-catering-indonesia",
    "title": "Wedding Catering Indonesia | Villa Wedding Specialists",
    "description": "Premium wedding catering for villa weddings in Indonesia. Customized menus, full service teams, and event coordination.",
    "date": "2026-05-17"
  },
  {
    "slug": "private-dining-indonesia",
    "title": "Private Dining Indonesia | At-Home Fine Dining Services",
    "description": "Experience at-home fine dining across Indonesia. Michelin-trained chefs, premium ingredients, and professional service.",
    "date": "2026-05-17"
  },
  {
    "slug": "healthy-meal-delivery-indonesia",
    "title": "Healthy Meal Delivery Indonesia | Chef-Prepared Villa Food",
    "description": "Gourmet healthy meal delivery and prep for Bali and Jakarta. Organic ingredients and nutrient-dense menus.",
    "date": "2026-05-17"
  },
  {
    "slug": "chef-for-hire-indonesia",
    "title": "Chef for Hire Indonesia | Personal Chef Services",
    "description": "Hire a personal chef in Indonesia for your villa or residence. Vetted professional chefs for daily or occasional service.",
    "date": "2026-05-17"
  },
  {
    "slug": "proposal-dinner",
    "title": "Proposal Dinner Bali | Romantic Private Chef Experiences",
    "description": "Plan the perfect proposal with a private chef dinner in your Bali villa. Intimate, styled, and unforgettable.",
    "date": "2026-05-17"
  },
  {
    "slug": "honeymoon-chef",
    "title": "Honeymoon Chef Bali | Private Villa Dining for Couples",
    "description": "Exclusive private chef services for honeymooners in Bali. Romantic breakfasts, sunset dinners, and intimate hosting.",
    "date": "2026-05-17"
  },
  {
    "slug": "private-chef-breakfast-bali",
    "title": "Private Chef Breakfast Bali | Poolside Villa Service",
    "description": "Wake up to a chef-prepared breakfast in your Bali villa. Floating trays, fresh juices, and international spreads.",
    "date": "2026-05-17"
  },
  {
    "slug": "private-chef-menteng",
    "title": "Private Chef Menteng | Diplomatic District Fine Dining",
    "description": "Discreet and professional private chef services for Jakarta’s Menteng district. Elite residential hospitality.",
    "date": "2026-05-17"
  }
]
